openapi: 3.0.0
info:
  title: SDR-GPT Research API
  description: API for researching and answering questions about companies and contacts
  version: 1.0.0

security:
  - ApiKeyAuth: []

servers:
  - url: https://api.example.com/v1

paths:
  /research/company:
    post:
      summary: Research Company
      description: Answer questions about a company based on available data
      operationId: researchCompany
      tags:
        - Research
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyResearchRequest'
      responses:
        '200':
          description: Successful research response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResearchResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /research/person:
    post:
      summary: Research Contact
      description: Answer questions about a contact based on available data
      operationId: researchContact
      tags:
        - Research
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactResearchRequest'
      responses:
        '200':
          description: Successful research response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResearchResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key for authentication
  schemas:
    BaseResearchRequest:
      type: object
      required:
        - question
        - responseType
      properties:
        question:
          type: string
          description: The question you want to ask
        responseType:
          type: string
          enum:
            - BOOL
            - TEXT
            - NUMBER
            - ENUM
          description: The format you expect the response to be in
        responseOptions:
          type: string
          description: Comma-separated list of possible options for ENUM response type
        context:
          type: string
          description: Additional context that might help answer the question

    CompanyResearchRequest:
      allOf:
        - $ref: '#/components/schemas/BaseResearchRequest'
        - type: object
          required:
              - website
          properties:
            company:
              type: object
              description: Company data used for research
              properties:
                name:
                  type: string
                website:
                  type: string
                industry:
                  type: string
                country:
                  type: string
                numEmployees:
                  type: integer
                annualRevenue:
                  type: number
                linkedinUrl:
                  type: string

    ContactResearchRequest:
      allOf:
        - $ref: '#/components/schemas/BaseResearchRequest'
        - type: object
          properties:
            contact:
              type: object
              description: Contact data used for research
              properties:
                email:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                title:
                  type: string
                company:
                  type: string
                industry:
                  type: string
                linkedinUrl:
                  type: string

    ResearchResponse:
      type: object
      properties:
        answerText:
          type: string
          description: Text answer to the question
        answerNumber:
          type: number
          description: Numerical answer when responseType is NUMBER
        details:
          type: string
          description: Additional details about the answer
        sources:
          type: string
          description: Sources used to derive the answer
        confidence:
          type: number
          description: Confidence score of the answer (1-10)

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message

  responses:
    Unauthorized:
      description: Missing or invalid API key
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
