openapi: 3.0.0
info:
  title: SDR-GPT Research API
  description: API for researching and answering questions about companies and contacts
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /research/company:
    post:
      summary: Research Company
      description: Answer questions about a company based on available data
      operationId: researchCompany
      tags:
        - Research
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyResearchRequest'
      responses:
        '200':
          description: Successful research response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResearchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /research/person:
    post:
      summary: Research Contact
      description: Answer questions about a contact based on available data
      operationId: researchContact
      tags:
        - Research
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactResearchRequest'
      responses:
        '200':
          description: Successful research response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResearchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    BaseResearchRequest:
      type: object
      required:
        - question
        - responseType
      properties:
        question:
          type: string
          description: The question you want to ask
        responseType:
          type: string
          enum:
            - BOOL
            - TEXT
            - NUMBER
            - ENUM
          description: The format you expect the response to be in
        responseOptions:
          type: string
          description: Comma-separated list of possible options for ENUM response type
        context:
          type: string
          description: Additional context that might help answer the question
        shouldSaveResponse:
          type: boolean
          description: Whether to save the response to object properties
        saveAnswerField:
          type: string
          description: Property field to save the answer to
        saveDetailsField:
          type: string
          description: Property field to save the details to

    CompanyResearchRequest:
      allOf:
        - $ref: '#/components/schemas/BaseResearchRequest'
        - type: object
          properties:
            company:
              type: object
              description: Company data used for research
              properties:
                hs_lastmodifieddate:
                  type: string
                  format: date-time
                createdate:
                  type: string
                  format: date-time
                name:
                  type: string
                domain:
                  type: string
                description:
                  type: string
                industry:
                  type: string
                country:
                  type: string
                numberofemployees:
                  type: integer
                annualrevenue:
                  type: number
                hubspot_owner_id:
                  type: string
                linkedin_company_page:
                  type: string
                website:
                  type: string

    ContactResearchRequest:
      allOf:
        - $ref: '#/components/schemas/BaseResearchRequest'
        - type: object
          properties:
            contact:
              type: object
              description: Contact data used for research
              properties:
                # Note: Specific contact properties would be defined here
                # They are referenced as CONTACT_PROPERTIES in the original spec
                email:
                  type: string
                firstname:
                  type: string
                lastname:
                  type: string
                phone:
                  type: string
                title:
                  type: string
                company:
                  type: string
                industry:
                  type: string
                linkedin_profile:
                  type: string
                # Additional fields can be added based on CONTACT_PROPERTIES

    ResearchResponse:
      type: object
      properties:
        answerText:
          type: string
          description: Text answer to the question
        answerNumber:
          type: number
          description: Numerical answer when responseType is NUMBER
        details:
          type: string
          description: Additional details about the answer
        sources:
          type: string
          description: Sources used to derive the answer
        confidence:
          type: number
          description: Confidence score of the answer (0-1)
        success:
          type: boolean
          description: Whether the research was completed successfully
        # Note: Additional output fields from HS_RESEARCH_CONTACT_OUTPUT_FIELDS would be added here

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'